### ISSUE TITLE
False alarms?

### ISSUE THREAD

**Issue by bep** [dvyukov/go-fuzz#10]
I had lots of fun with go-fuzz this afternoon. I will create a PR for the README later.

But first a question.

I get some crashes that I cannot reproduce by running them one-by-one. I'm having a hard time figuring out what went wrong by reading the output -- but these are repeatedly reported by two similar inputs (in two different scenarios), so I guess there are two bugs I have to identify.

I would be grateful for any hints about how to interpret the output below.

First:

```
SIGABRT: abort
PC=0x41f4fb

goroutine 1 [running]:
runtime.atomicload(0xc20803419c, 0x0)
	/tmp/go-fuzz-build681797842/src/runtime/atomic_amd64x.c:14 +0xb fp=0xc20802b698 sp=0xc20802b690
runtime.chanrecv(0x5db9a0, 0xc208034180, 0xc20802b7a8, 0x4007fb20bbd3000, 0x400000)
	/tmp/go-fuzz-build681797842/src/runtime/chan.go:354 +0xe1 fp=0xc20802b738 sp=0xc20802b698
runtime.selectnbrecv(0x5db9a0, 0xc20802b7a8, 0xc208034180, 0xc208000100)
	/tmp/go-fuzz-build681797842/src/runtime/chan.go:566 +0x41 fp=0xc20802b768 sp=0xc20802b738
github.com/BurntSushi/toml.(*lexer).nextItem(0xc2080341e0, 0x0, 0x0, 0x0, 0x0)
	/tmp/go-fuzz-build681797842/src/github.com/BurntSushi/toml/lex.go:84 +0xc0 fp=0xc20802b7d0 sp=0xc20802b768
github.com/BurntSushi/toml.(*parser).next(0xc208010620, 0x0, 0x0, 0x0, 0x0)
	/tmp/go-fuzz-build681797842/src/github.com/BurntSushi/toml/parse.go:97 +0x79 fp=0xc20802b880 sp=0xc20802b7d0
github.com/BurntSushi/toml.(*parser).topLevel(0xc208010620, 0xe, 0xc208010610, 0x1, 0x3)
	/tmp/go-fuzz-build681797842/src/github.com/BurntSushi/toml/parse.go:139 +0xb8 fp=0xc20802baa0 sp=0xc20802b880
github.com/BurntSushi/toml.parse(0xc208010540, 0x63, 0xc208010620, 0x0, 0x0)
	/tmp/go-fuzz-build681797842/src/github.com/BurntSushi/toml/parse.go:81 +0x659 fp=0xc20802bba0 sp=0xc20802baa0
github.com/BurntSushi/toml.Decode(0xc208010540, 0x63, 0x5d5dc0, 0xc20803e050, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/tmp/go-fuzz-build681797842/src/github.com/BurntSushi/toml/decode.go:113 +0x9d fp=0xc20802bcc0 sp=0xc20802bba0
github.com/spf13/hugo/parser.HandleTOMLMetaData(0xc208010460, 0x63, 0x63, 0x0, 0x0, 0x0, 0x0)
	/tmp/go-fuzz-build681797842/src/github.com/spf13/hugo/parser/frontmatter.go:254 +0x186 fp=0xc20802bd60 sp=0xc20802bcc0
github.com/spf13/hugo/parser.(*page).Metadata(0xc208036180, 0x0, 0x0, 0x0, 0x0)
	/tmp/go-fuzz-build681797842/src/github.com/spf13/hugo/parser/page.go:77 +0x14f fp=0xc20802bdd0 sp=0xc20802bd60
github.com/bep/gobep-fuzz/hugo/parser.Fuzz(0x7fb20b95f000, 0x6e, 0x100000, 0x2)
	/tmp/go-fuzz-build681797842/src/github.com/bep/gobep-fuzz/hugo/parser/main.go:31 +0x2d0 fp=0xc20802be70 sp=0xc20802bdd0
github.com/dvyukov/go-fuzz/go-fuzz-dep.Main(0x6a0050, 0x734220, 0x83c, 0x83c)
	/home/bep/dev/go/src/github.com/dvyukov/go-fuzz/go-fuzz-dep/main.go:64 +0x309 fp=0xc20802bf70 sp=0xc20802be70
main.main()
	/tmp/go-fuzz-build681797842/src/go-fuzz-main/main.go:10 +0x4e fp=0xc20802bf98 sp=0xc20802bf70
runtime.main()
	/tmp/go-fuzz-build681797842/src/runtime/proc.go:63 +0xf3 fp=0xc20802bfe0 sp=0xc20802bf98
runtime.goexit()
	/tmp/go-fuzz-build681797842/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20802bfe8 sp=0xc20802bfe0

rax     0x0
rbx     0x0
rcx     0xc208034180
rdx     0xc208034180
rdi     0xc20802b7c8
rsi     0x61
rbp     0x0
rsp     0xc20802b690
r8      0x64
r9      0x30
r10     0x30
r11     0x62abc0
r12     0x0
r13     0x0
r14     0x3
r15     0x10
rip     0x41f4fb
rflags  0x206
cs      0x33
fs      0x0
gs      0x0
exit status 2
```

Second:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x50 pc=0x4696bd]

goroutine 1 [running]:
github.com/spf13/hugo/hugolib.getShortcodeTemplate(0x0, 0x0, 0x0, 0x0, 0x0)
	/tmp/go-fuzz-build909848046/src/github.com/spf13/hugo/hugolib/shortcode.go:672 +0xad
github.com/spf13/hugo/hugolib.renderShortcode(0x0, 0x0, 0x0, 0x0, 0x0, 0xae9de0, 0xc2080fa8c0, 0x0, 0x0, 0x0, ...)
	/tmp/go-fuzz-build909848046/src/github.com/spf13/hugo/hugolib/shortcode.go:245 +0x13c
github.com/spf13/hugo/hugolib.extractAndRenderShortcodes(0xc2080fc618, 0x3, 0xc208038c00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/tmp/go-fuzz-build909848046/src/github.com/spf13/hugo/hugolib/shortcode.go:341 +0x57d
github.com/spf13/hugo/hugolib.HandleShortcodes(0xc2080fc618, 0x3, 0xc208038c00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/tmp/go-fuzz-build909848046/src/github.com/spf13/hugo/hugolib/shortcode.go:174 +0xcd
github.com/bep/gobep-fuzz/hugo/shortcode.Fuzz(0x7f7ded4cd000, 0x3, 0x100000, 0x0)
	/tmp/go-fuzz-build909848046/src/github.com/bep/gobep-fuzz/hugo/shortcode/main.go:29 +0x1bf
github.com/dvyukov/go-fuzz/go-fuzz-dep.Main(0xe19a08, 0x1018740, 0x3ab0, 0x3ab0)
	/home/bep/dev/go/src/github.com/dvyukov/go-fuzz/go-fuzz-dep/main.go:64 +0x309
main.main()
	/tmp/go-fuzz-build909848046/src/go-fuzz-main/main.go:10 +0x4e

goroutine 23 [runnable]:
github.com/spf13/hugo/hugolib.(*pagelexer).errorf(0xc208052090, 0xd8c650, 0x19, 0x0, 0x0, 0x0, 0xc208055500)
	/tmp/go-fuzz-build909848046/src/github.com/spf13/hugo/hugolib/shortcodeparser.go:314 +0xf6
github.com/spf13/hugo/hugolib.lexInsideShortcode(0xc208052090, 0xe19c08)
	/tmp/go-fuzz-build909848046/src/github.com/spf13/hugo/hugolib/shortcodeparser.go:705 +0x300
github.com/spf13/hugo/hugolib.(*pagelexer).runShortcodeLexer(0xc208052090)
	/tmp/go-fuzz-build909848046/src/github.com/spf13/hugo/hugolib/shortcodeparser.go:220 +0xc7
created by github.com/spf13/hugo/hugolib.newShortcodeLexer
	/tmp/go-fuzz-build909848046/src/github.com/spf13/hugo/hugolib/shortcodeparser.go:210 +0x19f
exit status 2
```

**Comment by dvyukov** [comment]
Hi Bjørn,

As for the first one (SIGABRT: abort), go-fuzz kills the test program with SIGABRT on timeout. The default timeout is 10 seconds, you can change it with -timeout flag. So it is either a real timeout (does the program run for a long time?) or just that particular execution was slowed down for some reason. The most common cause for such behavior that I observe is when test processes start consuming excessive amount of memory, cause swapping on machine and become exceedingly slow. Check whether the program consumes excessive amount of memory.

I will improve output to make it clear that this is a timeout.

As for the second one, it can be a memory corruption (each test process is reused for thousands of tests, so memory could have been corrupted during previous tests). Or a data race that leads to non-deterministic results (that particular execution crashed, but when you run the program second time timings are different and the program does not crash). Also, what version of Go are you using? I noticed that tip is very unstable recently.

Does it give you any hooks?

**Comment by bep** [comment]
Yes, thanks for that.

I run go 1.4.2.

The first one I now cannot reproduce. When it failed, it ran with my laptop unattended -- I'll blame the timeout on Linux hibernation or similar. I ran it now for 30 min / 10 mill execs with no crashes.

The second one is reproduce-able in go-fuzz; a subtle data race somewhere ...

**Comment by dvyukov** [comment]
> The second one is reproduce-able in go-fuzz; a subtle data race somewhere ...

Build the reproducer with -race?

Also, if you remove the relevant file in workdir/suppressions and workdir/crashers and restart go-fuzz, then you can see if it appears again or not.

**Comment by bep** [comment]
Will try the -race flag. Yes, I have done it the brutal way by wiping out the entire worker dir.

**Comment by bep** [comment]
The second was just a stupid mistake in my go-fuzz func. Thanks for the help.

**Comment by dvyukov** [comment]
ack, glad it is resolved
waiting for the pull request :)
