### ISSUE TITLE
nil deref in go-bindata-assetfs.(*AssetFS).Open

### ISSUE THREAD

**Issue by dvyukov** [dvyukov/go-fuzz#135]
As reported by @hydroflame  in #134.
Attempt to open web interface with tip go-fuzz and tip go-bindata-assetfs crashes:
```
goroutine 1211 [running]:
net/http.(*conn).serve.func1(0xc427d18e00)
	src/net/http/server.go:1492 +0x12a
panic(0x77e6e0, 0xc420010190)
	src/runtime/panic.go:458 +0x243
github.com/elazarl/go-bindata-assetfs.(*AssetFS).Open(0xc42771c7e0, 0x7e97d9, 0xb, 0xb, 0x0, 0xc4201805b0, 0x0)
	src/github.com/elazarl/go-bindata-assetfs/assetfs.go:148 +0x28d
net/http.serveFile(0x99dd60, 0xc420116a90, 0xc427a2a780, 0x998f20, 0xc42771c7e0, 0x7e97d9, 0xb, 0x42ca01)
	src/net/http/fs.go:364 +0xfb
net/http.(*fileHandler).ServeHTTP(0xc422edc7a0, 0x99dd60, 0xc420116a90, 0xc427a2a780)
	src/net/http/fs.go:526 +0xb4
main.(*Master).index(0xc42000c180, 0x99dd60, 0xc420116a90, 0xc427a2a780)
	src/github.com/dvyukov/go-fuzz/go-fuzz/master.go:134 +0xac
main.(*Master).(main.index)-fm(0x99dd60, 0xc420116a90, 0xc427a2a780)
	src/github.com/dvyukov/go-fuzz/go-fuzz/master.go:77 +0x48
net/http.HandlerFunc.ServeHTTP(0xc4202b20e0, 0x99dd60, 0xc420116a90, 0xc427a2a780)
	src/net/http/server.go:1727 +0x44
net/http.(*ServeMux).ServeHTTP(0x9bf780, 0x99dd60, 0xc420116a90, 0xc427a2a780)
	src/net/http/server.go:2023 +0x7f
net/http.serverHandler.ServeHTTP(0xc42000c300, 0x99dd60, 0xc420116a90, 0xc427a2a780)
	src/net/http/server.go:2203 +0x7d
net/http.(*conn).serve(0xc427d18e00, 0x99e5a0, 0xc425824dc0)
	src/net/http/server.go:1580 +0x4b7
created by net/http.(*Server).Serve
	src/net/http/server.go:2296 +0x447
```

**Comment by dvyukov** [comment]
@stephens2424 do you mind taking a look? Can we vendor these dependencies to prevent future issues?

**Comment by stephens2424** [comment]
I'll look this week, maybe tonight.
