### ISSUE TITLE
go-fuzz-dep: hang-up

### ISSUE THREAD

**Issue by mikioh** [dvyukov/go-fuzz#21]
Thanks for the nice stuff. Looks like go-fuzz-dep subprocesses on darwin/amd64 rarely hang up.

go version: git rev-parse HEAD
714291f2d80bab1599a866f266a4fc6546e61632
```
program hanged (timeout 10 seconds)

SIGABRT: abort
PC=0x51d6b m=0

goroutine 0 [idle]:
runtime.mach_semaphore_wait(0xd03, 0x0, 0x0, 0x2c3220, 0x2c3220, 0x23d060, 0x45de0, 0xffffffffffffffff, 0x0, 0x7fff5fbff76c, ...)
        /var/folders/7d/d3y9vsls2yd880k121jmzcyr0000gn/T/go-fuzz-build933145906/src/runtime/sys_darwin_amd64.s:407 +0xb
runtime.semasleep1(0xffffffffffffffff, 0x0)
        /var/folders/7d/d3y9vsls2yd880k121jmzcyr0000gn/T/go-fuzz-build933145906/src/runtime/os1_darwin.go:380 +0xee
runtime.semasleep.func1()
        /var/folders/7d/d3y9vsls2yd880k121jmzcyr0000gn/T/go-fuzz-build933145906/src/runtime/os1_darwin.go:396 +0x30
runtime.systemstack(0x7fff5fbff770)
        /var/folders/7d/d3y9vsls2yd880k121jmzcyr0000gn/T/go-fuzz-build933145906/src/runtime/asm_amd64.s:278 +0xb1
runtime.semasleep(0xffffffffffffffff, 0x0)
        /var/folders/7d/d3y9vsls2yd880k121jmzcyr0000gn/T/go-fuzz-build933145906/src/runtime/os1_darwin.go:397 +0x36
runtime.notesleep(0x23d468)
        /var/folders/7d/d3y9vsls2yd880k121jmzcyr0000gn/T/go-fuzz-build933145906/src/runtime/lock_sema.go:169 +0x112
runtime.stopm()
        /var/folders/7d/d3y9vsls2yd880k121jmzcyr0000gn/T/go-fuzz-build933145906/src/runtime/proc1.go:1110 +0x127
runtime.findrunnable(0xc20801c000, 0x0)
        /var/folders/7d/d3y9vsls2yd880k121jmzcyr0000gn/T/go-fuzz-build933145906/src/runtime/proc1.go:1491 +0x6c2
runtime.schedule()
        /var/folders/7d/d3y9vsls2yd880k121jmzcyr0000gn/T/go-fuzz-build933145906/src/runtime/proc1.go:1600 +0x285
runtime.exitsyscall0(0xc208000140)
        /var/folders/7d/d3y9vsls2yd880k121jmzcyr0000gn/T/go-fuzz-build933145906/src/runtime/proc1.go:2107 +0x183
runtime.mcall(0x7fff5fbff8f0)
        /var/folders/7d/d3y9vsls2yd880k121jmzcyr0000gn/T/go-fuzz-build933145906/src/runtime/asm_amd64.s:204 +0x5e

goroutine 1 [syscall]:
syscall.Syscall(0x4, 0x5, 0xc208051e80, 0x18, 0x12c9c0, 0x10, 0xc2080cf5b0)
        /var/folders/7d/d3y9vsls2yd880k121jmzcyr0000gn/T/go-fuzz-build933145906/src/syscall/asm_darwin_amd64.s:16 +0x5
syscall.write(0x5, 0xc208051e80, 0x18, 0x18, 0xc2080d2360, 0x0, 0x0)
        /var/folders/7d/d3y9vsls2yd880k121jmzcyr0000gn/T/go-fuzz-build933145906/src/syscall/zsyscall_darwin_amd64.go:1360 +0x62
syscall.Write(0x5, 0xc208051e80, 0x18, 0x18, 0xc2080d2360, 0x0, 0x0)
        /var/folders/7d/d3y9vsls2yd880k121jmzcyr0000gn/T/go-fuzz-build933145906/src/syscall/syscall_unix.go:176 +0x54
github.com/dvyukov/go-fuzz/go-fuzz-dep.FD.write(0x5, 0xc208051e80, 0x18, 0x18, 0x1fffe8, 0x0, 0x0)
        /swdev/src/github.com/dvyukov/go-fuzz/go-fuzz-dep/sys_posix.go:27 +0x52
github.com/dvyukov/go-fuzz/go-fuzz-dep.write(0x5, 0xc208051f18, 0x3, 0x3)
        /swdev/src/github.com/dvyukov/go-fuzz/go-fuzz-dep/main.go:83 +0x15b
github.com/dvyukov/go-fuzz/go-fuzz-dep.Main(0x1bffc0)
        /swdev/src/github.com/dvyukov/go-fuzz/go-fuzz-dep/main.go:46 +0x212
main.main()
        /var/folders/7d/d3y9vsls2yd880k121jmzcyr0000gn/T/go-fuzz-build933145906/src/go-fuzz-main/main.go:10 +0x2a

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /var/folders/7d/d3y9vsls2yd880k121jmzcyr0000gn/T/go-fuzz-build933145906/src/runtime/asm_amd64.s:1670 +0x1

rax    0xe
rbx    0xd03
rcx    0x7fff5fbff6f8
rdx    0x7fff5fbff770
rdi    0xd03
rsi    0x23d060
rbp    0x23d360
rsp    0x7fff5fbff6f8
r8     0x23d360
r9     0x0
r10    0x0
r11    0x286
r12    0x17c03e75
r13    0xeccf602d6
r14    0xeccf602d6
r15    0x23cda0
rip    0x51d6b
rflags 0x286
cs     0x7
fs     0x0
gs     0x0
exit status 2
```

**Comment by dvyukov** [comment]
Hi @mikioh 

Humm... I run it on darwin and never hit such hang...
Is it reproducible on your machine? Does it hang with other stack traces (this usually happens when the test is very slow on a particular input or allocates gigs of memory and causes swapping). Does it happen with go1.4 (it can be a runtime bug on tip)?

**Comment by mikioh** [comment]
Still failed to repro with tip or go1.4 on darwin/amd64. 

> Does it hang with other stack traces

No, it happened only twice until now, and both had the same stack trace as above.

>  (it can be a runtime bug on tip)?

Likely, I still encounter 0xdeaddeaddeaddead memory corruption issues with tip.

**Comment by dvyukov** [comment]
OK, let's close it for now, as it is not actionable. I believe this is a runtime bug. Feel free to repoen if you have more details.
