### ISSUE TITLE
SIGQUIT crashes go-fuzz

### ISSUE THREAD

**Issue by Crypt-iQ** [dvyukov/go-fuzz#283]
Calling SIGQUIT crashes go-fuzz:
```
\SIGQUIT: quit
PC=0x462813 m=0 sigcode=128

goroutine 9 [syscall]:
runtime.notetsleepg(0xe1d260, 0x208a3384, 0x0)
        /usr/local/go/src/runtime/lock_futex.go:227 +0x34 fp=0xc00009b760 sp=0xc00009b730 pc=0x40cb84
runtime.timerproc(0xe1d240)
        /usr/local/go/src/runtime/time.go:311 +0x2f1 fp=0xc00009b7d8 sp=0xc00009b760 pc=0x44f7e1
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00009b7e0 sp=0xc00009b7d8 pc=0x4608e1
created by runtime.(*timersBucket).addtimerLocked
        /usr/local/go/src/runtime/time.go:169 +0x10e

goroutine 1 [select (no cases)]:
main.main()
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/main.go:123 +0x625

goroutine 35 [chan receive]:
main.main.func1()
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/main.go:63 +0xa0
created by main.main
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/main.go:60 +0xde

goroutine 34 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 37 [IO wait]:
internal/poll.runtime_pollWait(0x7fefec3b4f08, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc00014a398, 0x72, 0x0, 0x0, 0x9d3c76)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc00014a380, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:384 +0x1f8
net.(*netFD).accept(0xc00014a380, 0x946920, 0x9b4360, 0x7fefec401080)
        /usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc000150300, 0xc0000ace90, 0xc0000ace98, 0x18)
        /usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc000150300, 0x9fa038, 0xc000104140, 0x7fefec401080, 0xc00014e020)
        /usr/local/go/src/net/tcpsock.go:261 +0x47
net/rpc.(*Server).Accept(0xc000104140, 0xa9d360, 0xc000150300)
        /usr/local/go/src/net/rpc/server.go:625 +0x69
main.coordinatorMain(0xa9d360, 0xc000150300)
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/coordinator.go:71 +0x387
created by main.main
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/main.go:95 +0x302

goroutine 52 [select]:
main.newTestee.func1(0xc0003ac000, 0x100000, 0x100000, 0xc000118480)
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/testee.go:201 +0xdf
created by main.newTestee
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/testee.go:191 +0x6fc

goroutine 8 [chan receive]:
main.coordinatorLoop(0xc000152100)
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/coordinator.go:89 +0x192
created by main.coordinatorMain
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/coordinator.go:67 +0x317

goroutine 41 [IO wait]:
internal/poll.runtime_pollWait(0x7fefec3b4d68, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc00014a118, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00014a100, 0xc0007dd000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x1cf
net.(*netFD).Read(0xc00014a100, 0xc0007dd000, 0x1000, 0x1000, 0xc00105b9c8, 0x40fafb, 0xc00105ba38)
        /usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00014e020, 0xc0007dd000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:184 +0x68
bufio.(*Reader).Read(0xc000140240, 0xc0007de000, 0x1, 0x9, 0x778a2d, 0xc00014a200, 0xc0001503c0)
        /usr/local/go/src/bufio/bufio.go:226 +0x26a
io.ReadAtLeast(0xa92e60, 0xc000140240, 0xc0007de000, 0x1, 0x9, 0x1, 0x77fca7, 0x924da0, 0x10)
        /usr/local/go/src/io/io.go:310 +0x87
io.ReadFull(...)
        /usr/local/go/src/io/io.go:329
encoding/gob.decodeUintReader(0xa92e60, 0xc000140240, 0xc0007de000, 0x9, 0x9, 0x0, 0x0, 0xc00105bc28, 0x7802d4)
        /usr/local/go/src/encoding/gob/decode.go:120 +0x6f
encoding/gob.(*Decoder).recvMessage(0xc00014a200, 0xc0001f3880)
        /usr/local/go/src/encoding/gob/decoder.go:81 +0x57
encoding/gob.(*Decoder).decodeTypeSequence(0xc00014a200, 0xaaa000, 0x199)
        /usr/local/go/src/encoding/gob/decoder.go:143 +0x10c
encoding/gob.(*Decoder).DecodeValue(0xc00014a200, 0x8f3d80, 0xc000150520, 0x16, 0x0, 0x0)
        /usr/local/go/src/encoding/gob/decoder.go:211 +0x10b
encoding/gob.(*Decoder).Decode(0xc00014a200, 0x8f3d80, 0xc000150520, 0x3be40, 0xc000104168)
        /usr/local/go/src/encoding/gob/decoder.go:188 +0x16d
net/rpc.(*gobServerCodec).ReadRequestHeader(0xc000130d20, 0xc000150520, 0x8eee40, 0xc000148800)
        /usr/local/go/src/net/rpc/server.go:397 +0x45
net/rpc.(*Server).readRequestHeader(0xc000104140, 0xa9ea20, 0xc000130d20, 0xc000148800, 0x16, 0xc0001f3880, 0xc0001bc501, 0x0, 0x0)
        /usr/local/go/src/net/rpc/server.go:583 +0x67
net/rpc.(*Server).readRequest(0xc000104140, 0xa9ea20, 0xc000130d20, 0xc000104140, 0xc0007de010, 0xc0007de020, 0xc000152300, 0xc000150000, 0x8eee00, 0xc0001f3880, ...)
        /usr/local/go/src/net/rpc/server.go:543 +0x5a
net/rpc.(*Server).ServeCodec(0xc000104140, 0xa9ea20, 0xc000130d20)
        /usr/local/go/src/net/rpc/server.go:458 +0x97
net/rpc.(*Server).ServeConn(0xc000104140, 0x7fefec401080, 0xc00014e020)
        /usr/local/go/src/net/rpc/server.go:449 +0x158
created by net/rpc.(*Server).Accept
        /usr/local/go/src/net/rpc/server.go:630 +0x55

goroutine 11 [IO wait]:
internal/poll.runtime_pollWait(0x7fefec3b4e38, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc000152418, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000152400, 0xc0007da000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x1cf
net.(*netFD).Read(0xc000152400, 0xc0007da000, 0x1000, 0x1000, 0xc0001c1be8, 0x40fafb, 0xc0001c1c58)
        /usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000010070, 0xc0007da000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:184 +0x68
bufio.(*Reader).Read(0xc0000c2780, 0xc0007d2b40, 0x1, 0x9, 0x0, 0x0, 0xc0001c1d70)
        /usr/local/go/src/bufio/bufio.go:226 +0x26a
io.ReadAtLeast(0xa92e60, 0xc0000c2780, 0xc0007d2b40, 0x1, 0x9, 0x1, 0x1, 0x0, 0x0)
        /usr/local/go/src/io/io.go:310 +0x87
io.ReadFull(...)
        /usr/local/go/src/io/io.go:329
encoding/gob.decodeUintReader(0xa92e60, 0xc0000c2780, 0xc0007d2b40, 0x9, 0x9, 0x407125, 0x432b7c, 0xc0001c1d48, 0x45d3e0)
        /usr/local/go/src/encoding/gob/decode.go:120 +0x6f
encoding/gob.(*Decoder).recvMessage(0xc000152480, 0x40700c)
        /usr/local/go/src/encoding/gob/decoder.go:81 +0x57
encoding/gob.(*Decoder).decodeTypeSequence(0xc000152480, 0xc0000ce700, 0xc0001c1e10)
        /usr/local/go/src/encoding/gob/decoder.go:143 +0x10c
encoding/gob.(*Decoder).DecodeValue(0xc000152480, 0x8f3dc0, 0xc000130d50, 0x16, 0x0, 0x0)
        /usr/local/go/src/encoding/gob/decoder.go:211 +0x10b
encoding/gob.(*Decoder).Decode(0xc000152480, 0x8f3dc0, 0xc000130d50, 0x0, 0x0)
        /usr/local/go/src/encoding/gob/decoder.go:188 +0x16d
net/rpc.(*gobClientCodec).ReadResponseHeader(0xc0000e5aa0, 0xc000130d50, 0xc000148780, 0x0)
        /usr/local/go/src/net/rpc/client.go:228 +0x45
net/rpc.(*Client).input(0xc0000c2840)
        /usr/local/go/src/net/rpc/client.go:109 +0xa5
created by net/rpc.NewClientWithCodec
        /usr/local/go/src/net/rpc/client.go:206 +0x89

goroutine 43 [select]:
main.(*Hub).loop(0xc00012a400)
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/hub.go:168 +0x235
created by main.newHub
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/hub.go:121 +0x892

goroutine 44 [IO wait]:
internal/poll.runtime_pollWait(0x7fefec3b4958, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc000140558, 0x72, 0x1, 0x18, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000140540, 0xc0007fc4f1, 0x18, 0x18, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x1cf
os.(*File).read(...)
        /usr/local/go/src/os/file_unix.go:259
os.(*File).Read(0xc000010150, 0xc0007fc4f1, 0x18, 0x18, 0x5e175382, 0xc0001bf828, 0x9)
        /usr/local/go/src/os/file.go:116 +0x71
io.ReadAtLeast(0xa93800, 0xc000010150, 0xc0007fc4f1, 0x18, 0x18, 0x18, 0x0, 0x0, 0xc0001bf890)
        /usr/local/go/src/io/io.go:310 +0x87
io.ReadFull(...)
        /usr/local/go/src/io/io.go:329
main.(*Testee).test(0xc0007fc480, 0xc00022b800, 0x109, 0x300, 0x8abdbe, 0xc00012a400, 0x7fefec020000, 0x10000, 0x210000, 0x7fefec130000, ...)
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/testee.go:290 +0x221
main.(*TestBinary).test(0xc0001ac0b0, 0xc00022b800, 0x109, 0x300, 0x10000, 0x210000, 0x0, 0x0, 0x0, 0x0, ...)
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/testee.go:118 +0xb4
main.(*Worker).minimizeInput(0xc0017b8000, 0xc00022b200, 0x300, 0x300, 0x10000, 0xc0001bfc10, 0xc002060000, 0x10000, 0x10000)
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/worker.go:410 +0x87b
main.(*Worker).triageInput(0xc0017b8000, 0xc00022b200, 0x300, 0x300, 0x2, 0x5)
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/worker.go:312 +0x55d
main.(*Worker).loop(0xc0017b8000)
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/worker.go:217 +0x72e
created by main.workerMain
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/worker.go:165 +0x9e0

goroutine 49 [IO wait]:
internal/poll.runtime_pollWait(0x7fefec3b4bc8, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc000140af8, 0x72, 0x100001, 0x100000, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000140ae0, 0xc0017ba000, 0x100000, 0x100000, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x1cf
os.(*File).read(...)
        /usr/local/go/src/os/file_unix.go:259
os.(*File).Read(0xc000010180, 0xc0017ba000, 0x100000, 0x100000, 0x1, 0xa93140, 0xc0000ae040)
        /usr/local/go/src/os/file.go:116 +0x71
main.newTestee.func1(0xc0017ba000, 0x100000, 0x100000, 0xc0007fc480)
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/testee.go:205 +0x172
created by main.newTestee
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/testee.go:191 +0x6fc

goroutine 53 [select]:
main.newTestee.func2(0xc000118480)
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/testee.go:228 +0xe2
created by main.newTestee
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/testee.go:224 +0x71e

goroutine 54 [select]:
main.newTestee.func3(0xc000118480)
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/testee.go:248 +0xa6
created by main.newTestee
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/testee.go:247 +0x740

goroutine 12 [IO wait]:
internal/poll.runtime_pollWait(0x7fefec3b46e8, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc0000c3158, 0x72, 0x1, 0x18, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0000c3140, 0xc0001184f1, 0x18, 0x18, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x1cf
os.(*File).read(...)
        /usr/local/go/src/os/file_unix.go:259
os.(*File).Read(0xc00014e068, 0xc0001184f1, 0x18, 0x18, 0x5e175382, 0xc0001c5560, 0x9)
        /usr/local/go/src/os/file.go:116 +0x71
io.ReadAtLeast(0xa93800, 0xc00014e068, 0xc0001184f1, 0x18, 0x18, 0x18, 0x0, 0x10000, 0xc0001c55c8)
        /usr/local/go/src/io/io.go:310 +0x87
io.ReadFull(...)
        /usr/local/go/src/io/io.go:329
main.(*Testee).test(0xc000118480, 0xc000da7ef0, 0x48, 0x48, 0x1, 0x9e0af, 0x7fefe4bda000, 0x10000, 0x210000, 0x7fefe4cea000, ...)
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/testee.go:290 +0x221
main.(*TestBinary).test(0xc0001ac210, 0xc000da7ef0, 0x48, 0x48, 0x0, 0x10000, 0xc0002060a6, 0xc0001c5770, 0x44b3df, 0x5, ...)
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/testee.go:118 +0xb4
main.(*Worker).testInputImpl(0xc0017b80e0, 0xc0001ac210, 0xc000da7ef0, 0x48, 0x48, 0x1, 0x9, 0x906960, 0xc000206001, 0xc000da7ef0)
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/worker.go:606 +0xfc
main.(*Worker).testInput(...)
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/worker.go:591
main.(*Worker).processSonarData.func1(0xc000da7ef0, 0x48, 0x48)
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/sonar.go:116 +0x63
main.(*Worker).processSonarData.func2(0xc0005d3ae0, 0x48, 0x48, 0xc0008c1f68, 0x1, 0x8, 0xc0002060a5, 0x1, 0x1)
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/sonar.go:147 +0x42c
main.(*Worker).processSonarData.func3(0xc0008c1f68, 0x1, 0x8, 0xc0008c1f70, 0x1, 0x8)
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/sonar.go:193 +0x25e
main.(*Worker).processSonarData(0xc0017b80e0, 0xc0005d3ae0, 0x48, 0x48, 0x7fefe4ada000, 0x549d2, 0x100000, 0x0, 0x54900)
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/sonar.go:238 +0x6a2
main.(*Worker).loop(0xc0017b80e0)
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/worker.go:253 +0xcec
created by main.workerMain
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/worker.go:165 +0x9e0

goroutine 16 [IO wait]:
internal/poll.runtime_pollWait(0x7fefec3b4478, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc0000c35d8, 0x72, 0x100001, 0x100000, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0000c35c0, 0xc000a40000, 0x100000, 0x100000, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x1cf
os.(*File).read(...)
        /usr/local/go/src/os/file_unix.go:259
os.(*File).Read(0xc00014e228, 0xc000a40000, 0x100000, 0x100000, 0x1, 0x0, 0x0)
        /usr/local/go/src/os/file.go:116 +0x71
main.newTestee.func1(0xc000a40000, 0x100000, 0x100000, 0xc0007fc300)
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/testee.go:205 +0x172
created by main.newTestee
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/testee.go:191 +0x6fc

goroutine 50 [select]:
main.newTestee.func2(0xc0007fc300)
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/testee.go:228 +0xe2
created by main.newTestee
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/testee.go:224 +0x71e

goroutine 51 [select]:
main.newTestee.func3(0xc0007fc300)
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/testee.go:248 +0xa6
created by main.newTestee
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/testee.go:247 +0x740

goroutine 66 [select]:
main.newTestee.func2(0xc0007fc480)
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/testee.go:228 +0xe2
created by main.newTestee
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/testee.go:224 +0x71e

goroutine 67 [select]:
main.newTestee.func3(0xc0007fc480)
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/testee.go:248 +0xa6
created by main.newTestee
        /home/eugene/go/src/github.com/dvyukov/go-fuzz/go-fuzz/testee.go:247 +0x740

rax    0xfffffffffffffffc
rbx    0x208a3384
rcx    0x462813
rdx    0x0
rdi    0xe1d260
rsi    0x80
rbp    0xc00009b6e8
rsp    0xc00009b6a0
r8     0x0
r9     0x0
r10    0xc00009b6d8
r11    0x206
r12    0xae53e14d6d1
r13    0x5
r14    0xae53e14d6d1
r15    0x0
rip    0x462813
rflags 0x206
cs     0x33
fs     0x0
gs     0x0
```

Should this be the case?

**Comment by josharian** [comment]
SIGQUIT causes all Go programs (not just go-fuzz) to stop and dump stack traces. It’s pretty useful. :)

**Comment by Crypt-iQ** [comment]
Ah @josharian thanks, closing :)
