### ISSUE TITLE
strange crasher

### ISSUE THREAD

**Issue by andrewchambers** [dvyukov/go-fuzz#4]
Ran fuzzer for a short time, in crashers, got HASH.output with panic seemingly unrelated to my program.
```
fatal error: schedule: spinning with local work

runtime stack:
runtime.throw(0x594ad0, 0x22)
	/tmp/go-fuzz-build832835859/src/runtime/panic.go:543 +0x96
runtime.schedule()
	/tmp/go-fuzz-build832835859/src/runtime/proc1.go:1477 +0x247
runtime.mstart1()
	/tmp/go-fuzz-build832835859/src/runtime/proc1.go:743 +0x129
runtime.mstart()
	/tmp/go-fuzz-build832835859/src/runtime/proc1.go:703 +0x72

goroutine 1 [runnable]:
syscall.Syscall(0x0, 0x4, 0xc20803dea8, 0x8, 0x8, 0x8, 0x0)
	/tmp/go-fuzz-build832835859/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x4, 0xc20803dea8, 0x8, 0x8, 0x547760, 0x0, 0x0)
	/tmp/go-fuzz-build832835859/src/syscall/zsyscall_linux_amd64.go:792 +0x62
syscall.Read(0x4, 0xc20803dea8, 0x8, 0x8, 0x10, 0x0, 0x0)
	/tmp/go-fuzz-build832835859/src/syscall/syscall_unix.go:160 +0x54
github.com/dvyukov/go-fuzz/go-fuzz-dep.read(0x4, 0xc20803df20)
	/home/andrew/Desktop/gosrc/src/github.com/dvyukov/go-fuzz/go-fuzz-dep/main.go:54 +0xc6
github.com/dvyukov/go-fuzz/go-fuzz-dep.Main(0x5aac48)
	/home/andrew/Desktop/gosrc/src/github.com/dvyukov/go-fuzz/go-fuzz-dep/main.go:37 +0x3c
main.main()
	/tmp/go-fuzz-build832835859/src/go-fuzz-main/main.go:10 +0x2a

```

**Comment by dvyukov** [comment]
This is a known bug on tip:
https://github.com/golang/go/issues/10573
If you find a similar bug that is not known yet, or on release branch, that would be a great outcome.

**Comment by dvyukov** [comment]
THere is fix mailed:
https://go-review.googlesource.com/#/c/9332/

**Comment by dvyukov** [comment]
The fix is merged.

**Comment by andrewchambers** [comment]
Thanks, it is fixed on my end too.
