### ISSUE TITLE
panic: bad in cover.go

### ISSUE THREAD

**Issue by thoj** [dvyukov/go-fuzz#69]
After running a few seconds. Seems quite random.

```
panic: bad

goroutine 18 [running]:
main.compareCover(0xc208ef0000, 0x10000, 0x10000, 0x7f050b169000, 0x10000, 0x210000, 0xc208f11160)
        /src/github.com/dvyukov/go-fuzz/go-fuzz/cover.go:22 +0x141
main.(*Hub).updateMaxCover(0xc208040400, 0x7f050b169000, 0x10000, 0x210000, 0x0)
        /src/github.com/dvyukov/go-fuzz/go-fuzz/hub.go:288 +0xd1
main.(*Slave).noteNewInput(0xc20807a1c0, 0xc208f12440, 0xc, 0xe, 0x7f050b169000, 0x10000, 0x210000, 0x1, 0x1, 0x5)
        /src/github.com/dvyukov/go-fuzz/go-fuzz/slave.go:582 +0x74
main.(*Slave).testInputImpl(0xc20807a1c0, 0xc208042630, 0xc208f12440, 0xc, 0xe, 0x1, 0x5, 0x7f050b279000, 0x0, 0x100000)
        /src/github.com/dvyukov/go-fuzz/go-fuzz/slave.go:573 +0x368
main.(*Slave).testInput(0xc20807a1c0, 0xc208f12440, 0xc, 0xe, 0x1, 0x5)
        /src/github.com/dvyukov/go-fuzz/go-fuzz/slave.go:553 +0x66
main.(*Slave).smash(0xc20807a1c0, 0xc208280310, 0xe, 0xe, 0x0)
        /src/github.com/dvyukov/go-fuzz/go-fuzz/slave.go:548 +0x1854
main.(*Slave).triageInput(0xc20807a1c0, 0xc208280310, 0xe, 0xe, 0x0, 0x1, 0x1)
        /src/github.com/dvyukov/go-fuzz/go-fuzz/slave.go:286 +0x5bf
main.(*Slave).loop(0xc20807a1c0)
        /src/github.com/dvyukov/go-fuzz/go-fuzz/slave.go:151 +0x67c
created by main.slaveMain
        /src/github.com/dvyukov/go-fuzz/go-fuzz/slave.go:127 +0x9cd

goroutine 1 [select (no cases)]:
main.main()
        /src/github.com/dvyukov/go-fuzz/go-fuzz/main.go:91 +0x1b3

goroutine 9 [IO wait]:
net.(*pollDesc).Wait(0xc208010290, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010290, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208010230, 0x0, 0x7f050d525d30, 0xc208979178)
        /usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20802c018, 0xc20805add0, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc20802c018, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:244 +0x4c
net/rpc.(*Server).Accept(0xc20800a100, 0x7f050d526518, 0xc20802c018)
        /usr/local/go/src/net/rpc/server.go:617 +0x3c
main.masterMain(0x7f050d526518, 0xc20802c018)
        /src/github.com/dvyukov/go-fuzz/go-fuzz/master.go:68 +0x633
created by main.main
        /src/github.com/dvyukov/go-fuzz/go-fuzz/main.go:81 +0x45c

goroutine 6 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 8 [chan receive]:
main.func·001()
        /src/github.com/dvyukov/go-fuzz/go-fuzz/main.go:52 +0x147
created by main.main
        /src/github.com/dvyukov/go-fuzz/go-fuzz/main.go:61 +0xe6

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 37 [select]:
main.func·011()
        /src/github.com/dvyukov/go-fuzz/go-fuzz/testee.go:185 +0x5a6
created by main.newTestee
        /src/github.com/dvyukov/go-fuzz/go-fuzz/testee.go:206 +0xfc3

goroutine 11 [chan receive]:
main.masterLoop(0xc2080a4100)
        /src/github.com/dvyukov/go-fuzz/go-fuzz/master.go:86 +0x87
created by main.masterMain
        /src/github.com/dvyukov/go-fuzz/go-fuzz/master.go:64 +0x563

goroutine 13 [IO wait]:
net.(*pollDesc).Wait(0xc208010370, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010370, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208010310, 0xc20899f000, 0x1000, 0x1000, 0x0, 0x7f050d525d30, 0xc2080eaba8)
        /usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20802c040, 0xc20899f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:121 +0xdc
bufio.(*Reader).fill(0xc20804e5a0)
        /usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Read(0xc20804e5a0, 0xc208978f20, 0x1, 0x9, 0xc2080a4550, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:174 +0x26c
io.ReadAtLeast(0x7f050d527740, 0xc20804e5a0, 0xc208978f20, 0x1, 0x9, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:298 +0xf1
io.ReadFull(0x7f050d527740, 0xc20804e5a0, 0xc208978f20, 0x1, 0x9, 0x5ceb5d, 0x0, 0x0)
        /usr/local/go/src/io/io.go:316 +0x6d
encoding/gob.decodeUintReader(0x7f050d527740, 0xc20804e5a0, 0xc208978f20, 0x9, 0x9, 0x0, 0x1, 0x0, 0x0)
        /usr/local/go/src/encoding/gob/decode.go:121 +0x99
encoding/gob.(*Decoder).recvMessage(0xc2080a4500, 0x1)
        /usr/local/go/src/encoding/gob/decoder.go:76 +0x55
encoding/gob.(*Decoder).decodeTypeSequence(0xc2080a4500, 0xc20898a100, 0x16)
        /usr/local/go/src/encoding/gob/decoder.go:140 +0x47
encoding/gob.(*Decoder).DecodeValue(0xc2080a4500, 0x6e6ca0, 0xc20898a120, 0x16, 0x0, 0x0)
        /usr/local/go/src/encoding/gob/decoder.go:208 +0x192
encoding/gob.(*Decoder).Decode(0xc2080a4500, 0x6e6ca0, 0xc20898a120, 0x0, 0x0)
        /usr/local/go/src/encoding/gob/decoder.go:185 +0x297
net/rpc.(*gobClientCodec).ReadResponseHeader(0xc2089c09f0, 0xc20898a120, 0x0, 0x0)
        /usr/local/go/src/net/rpc/client.go:223 +0x5e
net/rpc.(*Client).input(0xc20804e660)
        /usr/local/go/src/net/rpc/client.go:109 +0xb6
created by net/rpc.NewClientWithCodec
        /usr/local/go/src/net/rpc/client.go:201 +0xd0

goroutine 14 [IO wait]:
net.(*pollDesc).Wait(0xc2080111e0, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080111e0, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208011180, 0xc2089a3000, 0x1000, 0x1000, 0x0, 0x7f050d525d30, 0xc20897c598)
        /usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20802c1c8, 0xc2089a3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:121 +0xdc
bufio.(*Reader).fill(0xc20804ec00)
        /usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Read(0xc20804ec00, 0xc2089791b0, 0x1, 0x9, 0x5c5a0a, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:174 +0x26c
io.ReadAtLeast(0x7f050d527740, 0xc20804ec00, 0xc2089791b0, 0x1, 0x9, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:298 +0xf1
io.ReadFull(0x7f050d527740, 0xc20804ec00, 0xc2089791b0, 0x1, 0x9, 0x1, 0x0, 0x0)
        /usr/local/go/src/io/io.go:316 +0x6d
encoding/gob.decodeUintReader(0x7f050d527740, 0xc20804ec00, 0xc2089791b0, 0x9, 0x9, 0x0, 0x1, 0x0, 0x0)
        /usr/local/go/src/encoding/gob/decode.go:121 +0x99
encoding/gob.(*Decoder).recvMessage(0xc2080a4580, 0xc208134240)
        /usr/local/go/src/encoding/gob/decoder.go:76 +0x55
encoding/gob.(*Decoder).decodeTypeSequence(0xc2080a4580, 0xc20897b400, 0x16)
        /usr/local/go/src/encoding/gob/decoder.go:140 +0x47
encoding/gob.(*Decoder).DecodeValue(0xc2080a4580, 0x6e6c40, 0xc20897b480, 0x16, 0x0, 0x0)
        /usr/local/go/src/encoding/gob/decoder.go:208 +0x192
encoding/gob.(*Decoder).Decode(0xc2080a4580, 0x6e6c40, 0xc20897b480, 0x0, 0x0)
        /usr/local/go/src/encoding/gob/decoder.go:185 +0x297
net/rpc.(*gobServerCodec).ReadRequestHeader(0xc20898a270, 0xc20897b480, 0x0, 0x0)
        /usr/local/go/src/net/rpc/server.go:402 +0x5e
net/rpc.(*Server).readRequestHeader(0xc20800a100, 0x7f050d52bbc0, 0xc20898a270, 0x0, 0x0, 0xc20897b480, 0xc208979100, 0x0, 0x0)
        /usr/local/go/src/net/rpc/server.go:575 +0x97
net/rpc.(*Server).readRequest(0xc20800a100, 0x7f050d52bbc0, 0xc20898a270, 0xc2080a4400, 0xc20897aee0, 0x6e2ce0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/rpc/server.go:542 +0xa2
net/rpc.(*Server).ServeCodec(0xc20800a100, 0x7f050d52bbc0, 0xc20898a270)
        /usr/local/go/src/net/rpc/server.go:461 +0x6d
net/rpc.(*Server).ServeConn(0xc20800a100, 0x7f050d52baa8, 0xc20802c1c8)
        /usr/local/go/src/net/rpc/server.go:453 +0x208
created by net/rpc.(*Server).Accept
        /usr/local/go/src/net/rpc/server.go:621 +0x1f3

goroutine 16 [select]:
main.(*Hub).loop(0xc208040400)
        /src/github.com/dvyukov/go-fuzz/go-fuzz/hub.go:152 +0x22d1
created by main.newHub
        /src/github.com/dvyukov/go-fuzz/go-fuzz/hub.go:115 +0xe8b

goroutine 38 [select]:
main.func·012()
        /src/github.com/dvyukov/go-fuzz/go-fuzz/testee.go:212 +0x300
created by main.newTestee
        /src/github.com/dvyukov/go-fuzz/go-fuzz/testee.go:229 +0x1022

goroutine 39 [select]:
main.func·013()
        /src/github.com/dvyukov/go-fuzz/go-fuzz/testee.go:232 +0x143
created by main.newTestee
        /src/github.com/dvyukov/go-fuzz/go-fuzz/testee.go:237 +0x107d

goroutine 29 [syscall]:
syscall.Syscall(0x0, 0x10, 0xc209170000, 0x100000, 0x0, 0xc208976f60, 0xc20804fd40)
        /usr/local/go/src/syscall/asm_linux_amd64.s:21 +0x5
syscall.read(0x10, 0xc209170000, 0x100000, 0x100000, 0xc208976f60, 0x0, 0x0)
        /usr/local/go/src/syscall/zsyscall_linux_amd64.go:867 +0x6e
syscall.Read(0x10, 0xc209170000, 0x100000, 0x100000, 0x2, 0x0, 0x0)
        /usr/local/go/src/syscall/syscall_unix.go:136 +0x58
os.(*File).read(0xc20802c8f8, 0xc209170000, 0x100000, 0x100000, 0x2, 0x0, 0x0)
        /usr/local/go/src/os/file_unix.go:191 +0x5e
os.(*File).Read(0xc20802c8f8, 0xc209170000, 0x100000, 0x100000, 0x100000, 0x0, 0x0)
        /usr/local/go/src/os/file.go:95 +0x91
main.func·011()
        /src/github.com/dvyukov/go-fuzz/go-fuzz/testee.go:189 +0x198
created by main.newTestee
        /src/github.com/dvyukov/go-fuzz/go-fuzz/testee.go:206 +0xfc3

goroutine 30 [select]:
main.func·012()
        /src/github.com/dvyukov/go-fuzz/go-fuzz/testee.go:212 +0x300
created by main.newTestee
        /src/github.com/dvyukov/go-fuzz/go-fuzz/testee.go:229 +0x1022

goroutine 31 [select]:
main.func·013()
        /src/github.com/dvyukov/go-fuzz/go-fuzz/testee.go:232 +0x143
created by main.newTestee
        /src/github.com/dvyukov/go-fuzz/go-fuzz/testee.go:237 +0x107d
```

**Comment by dvyukov** [comment]
How can I reproduce it?
On what go-fuzz commit are you?
What os/arch?

**Comment by thoj** [comment]
I had this info typed up but i never submitted it :'(

commit: a05cc646124f4f103d9bd41629ddc8dcaf970c04
Arch: Linux vmr4linux 2.6.32-5-amd64 #1 SMP Tue May 13 16:34:35 UTC 2014 x86_64 GNU/Linux

I was testing it on my https://github.com/thoj/go-ircevent irc library. 

The corpus i used is here:https://jager.no/owncloud/index.php/s/0pIxYZF0LiRwA7q

First time using this kind of Fuzzing library so i may have done something very stupid. ;)

**Comment by thoj** [comment]
Probably a terrible idea but i removed the panic in cover.go and ran tests fine. Even found a couple of parser bugs! :)

**Comment by dvyukov** [comment]
Uh, I left a debug check enabled. It verifies that a fast assembly version of a function produces the same results as a slow Go version. It is not meant to fail. But I think what happens in your case is that your test has some background goroutines that continue to write to code coverage array after Fuzz function invocation completes. As the result fast and slow functions produce different results, because they operate on different input data.

What you did it OK. The  1516992 commit disables the debug check entirely. It also makes execution somewhat faster.

Thanks for the report!

**Comment by dvyukov** [comment]
@thoj Btw, I see that here:
https://github.com/thoj/go-ircevent/blob/master/irc.go#L89
you do:

// +build gofuzz
func Fuzz(data []byte) int {

Build tags do not work this way, they must be at the top of the file. So now your package exports Fuzz function. You need to put Fuzz function into a separate file and say " // +build gofuzz" on top of that file, then then file will be compiled into the package only in go-fuzz build.

**Comment by thoj** [comment]
Ah i see :) Thank you!
