### ISSUE TITLE
panic: runtime error: index out of range (versifier)

### ISSUE THREAD

**Issue by kisielk** [dvyukov/go-fuzz#83]
Running goroutine stack trace:
```
$ go-fuzz -workdir=fuzz -bin=securecookie-fuzz.zip 
2015/08/18 11:44:35 slaves: 4, corpus: 100 (3s ago), crashers: 0, restarts: 1/0, execs: 0 (0/sec), cover: 0, uptime: 3s
2015/08/18 11:44:38 slaves: 4, corpus: 100 (6s ago), crashers: 0, restarts: 1/0, execs: 0 (0/sec), cover: 0, uptime: 6s
2015/08/18 11:44:41 slaves: 4, corpus: 100 (9s ago), crashers: 0, restarts: 1/6771, execs: 54173 (5953/sec), cover: 0, uptime: 9s
2015/08/18 11:44:44 slaves: 4, corpus: 100 (12s ago), crashers: 0, restarts: 1/8801, execs: 105620 (8756/sec), cover: 0, uptime: 12s
panic: runtime error: index out of range

goroutine 31 [running]:
github.com/dvyukov/go-fuzz/go-fuzz/versifier.structureKeyValue(0xc8203f6a80, 0x4, 0x4, 0x0, 0x0, 0x0)
	/Users/kamil/src/github.com/dvyukov/go-fuzz/go-fuzz/versifier/versifier.go:695 +0x4a7
github.com/dvyukov/go-fuzz/go-fuzz/versifier.structure(0xc8203f6a80, 0x4, 0x4, 0x0, 0x0, 0x0)
	/Users/kamil/src/github.com/dvyukov/go-fuzz/go-fuzz/versifier/versifier.go:575 +0xdd
github.com/dvyukov/go-fuzz/go-fuzz/versifier.BuildVerse(0x0, 0xc82008ba20, 0x14c, 0x14c, 0x10000)
	/Users/kamil/src/github.com/dvyukov/go-fuzz/go-fuzz/versifier/versifier.go:55 +0x1b9
main.(*Hub).loop(0xc8200b0a00)
	/Users/kamil/src/github.com/dvyukov/go-fuzz/go-fuzz/hub.go:236 +0x1c2c
created by main.newHub
	/Users/kamil/src/github.com/dvyukov/go-fuzz/go-fuzz/hub.go:115 +0xe83
```

Complete trace is here:
https://gist.github.com/kisielk/b3faaf4cbde1a5d026db

**Comment by kisielk** [comment]
I'm able to restart it and have it run for 20-30 seconds, but it crashes reliably after that.

**Comment by dvyukov** [comment]
versifier.go:695 is a continue statement in the latest sources:
https://github.com/dvyukov/go-fuzz/blob/master/go-fuzz/versifier/versifier.go
what version are you using?

**Comment by kisielk** [comment]
Hm, I had the same version actually but I guess perhaps that particular binary never got `go installed`ed, as it seems to be working fine after that...

**Comment by dvyukov** [comment]
closing then
please reopen if it happens again
